cb:
  PREFIX: §7[§6Module§7] §r
  START_PREFIX: ' §7>> §r'
  NO_PERMISSIONS: §cYou do not have permissions for that!
  NO_PLAYER: §cYou must be a player to use that!
  NO_COMMAND_FOUND: §cThat command do not exists!
  NO_NUMBER: §cThats not a normal number!
  NO_PLAYER_FOUND: §cThis Player doesn't exists!
  WORLD_NOT_FOUND: §cThis World doesn't exists!
  ON_LOAD: §7[§6Module§7] §r§aThe Plugin is loaded.
  ON_START: §7[§6Module§7] §r§aThe Plugin is started.
  ON_STOP: §7[§6Module§7] §r§aThe Plugin is stopped.
