name: LcraftAPI
version: '1.0.0'
main: de.lcraft.api.plugin.APIPluginMain
api-version: 1.17
authors:
  - LPD
  - Lcraft Developers
description: 'Das ist mein Plugin/API für weitere Module/Plugins von meiner Sorte.'
website: lcraft.de