name: LcraftAPI
version: '${project.version}'
main: de.lcraft.api.plugin.APIPluginMain
api-version: 1.17
authors:
  - LPD
  - Lcraft Developers
description: '${project.description}'
website: lcraft.de
