name: LcraftAPI
version: '1.0.3'
main: de.lcraft.api.utils.minecraft.spigot.SpigotClass
api-version: 1.17
authors:
  - LPD
  - Lcraft Developers
description: '${project.description}'
website: lcraft.de