# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
     branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch of Gituhb
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'

      - name: Step 3 - Build with Maven
        run: mvn -B package --file pom.xml

      - name: Step 4 - Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: LPDMinecraft
          server-password: MAVENSECRETTOKEN

      - name: Step 5 - Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.LPDMinecraft }}
          MAVEN_PASSWORD: ${{ secrets.MAVENSECRETTOKEN }}


